package main

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/maccavelli/go-llmprovider-sdk/llmprovider"
	"github.com/maccavelli/prepare-commit-msg/internal/config"
	"github.com/maccavelli/prepare-commit-msg/internal/git"
)

func TestCleanLLMOutput(t *testing.T) {
	cases := []struct {
		input    string
		expected string
	}{
		{"", ""},
		{"   ", ""},
		{
			"```\nfeat: my message\n```",
			"feat: my message",
		},
		{
			"Here is the commit message:\n\nfeat: some message\n",
			"feat: some message",
		},
		{
			"Generate a commit message:\n---",
			"",
		},
		{
			"```json\n{bad}\n```\nfeat: test",
			"{bad}\nfeat: test",
		},
		{
			"feat: crlf\r\n\r\nbody\r\n",
			"feat: crlf\n\nbody",
		},
	}

	for _, c := range cases {
		out := cleanLLMOutput(c.input)
		if out != c.expected {
			t.Errorf("cleanLLMOutput(%q) = %q; want %q", c.input, out, c.expected)
		}
	}
}

func TestBuildPrompt(t *testing.T) {
	info := &git.Info{
		Files:     []string{"main.go"},
		Stats:     "Scripts: 1",
		Additions: 5,
		Deletions: 2,
		Diff:      "mock diff",
	}
	out := buildPrompt(info)
	if !strings.Contains(out, "main.go") || !strings.Contains(out, "Scripts: 1") {
		t.Error("buildPrompt missing expected info")
	}
}

func TestWriteMessage(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "COMMIT_EDITMSG")
	if err := os.WriteFile(path, []byte("# existing"), 0o644); err != nil {
		t.Fatal(err)
	}

	info := &git.Info{Files: []string{"test.go"}, Additions: 1, Deletions: 0, Stats: "Scripts: 1"}
	if err := writeMessage(path, "feat: test", info); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	text := string(data)
	if !strings.Contains(text, "feat: test") {
		t.Error("missing message")
	}
	if !strings.Contains(text, "# AI-generated") {
		t.Error("missing metadata comment")
	}
	if !strings.Contains(text, "# existing") {
		t.Error("did not preserve existing content")
	}

	if err := writeMessage("/nonexistent/dir/file", "hello", info); err == nil {
		t.Error("expected IO error")
	}
}

func TestShouldSkipSource(t *testing.T) {
	cases := map[string]bool{
		"":         false,
		"template": false,
		"message":  true,
		"merge":    true,
		"squash":   true,
		"commit":   true,
		"unknown":  true,
	}
	for src, want := range cases {
		if got := shouldSkipSource(src); got != want {
			t.Errorf("shouldSkipSource(%q)=%v want %v", src, got, want)
		}
	}
}

func TestRunAnalyzer(t *testing.T) {
	oldHook := generateWithRetry
	defer func() { generateWithRetry = oldHook }()

	conf := &config.Config{
		ActiveProvider: "openai",
		Providers: map[string]config.ProviderConfig{
			"openai": {APIKey: "test", Model: "bad-model", FallbackModels: []string{"good-model"}},
			"claude": {APIKey: "test", Model: "bad-model", FallbackModels: []string{"good-model"}},
			"gemini": {APIKey: "test", Model: "bad-model", FallbackModels: []string{"good-model"}},
		},
		TimeoutSeconds: 5,
	}
	config.ApplyDefaults(conf)

	info := &git.Info{Files: []string{"app.go"}, Additions: 1, Deletions: 1}

	dir := t.TempDir()
	msgPath := filepath.Join(dir, "COMMIT_EDITMSG")
	if err := os.WriteFile(msgPath, []byte(""), 0o644); err != nil {
		t.Fatal(err)
	}

	var fallbackAttempted bool
	generateWithRetry = func(ctx context.Context, p llmprovider.Provider, prompt string, retries int, delay time.Duration) (string, error) {
		if !fallbackAttempted {
			fallbackAttempted = true
			return "", fmt.Errorf("first model fails")
		}
		return "feat: valid message generated by fallback", nil
	}

	if err := runAnalyzer(msgPath, conf, info); err != nil {
		t.Errorf("expected success on fallback: %v", err)
	}

	fallbackAttempted = false
	generateWithRetry = func(ctx context.Context, p llmprovider.Provider, prompt string, retries int, delay time.Duration) (string, error) {
		return "", fmt.Errorf("all fail")
	}
	err := runAnalyzer(msgPath, conf, info)
	if err == nil || !strings.Contains(err.Error(), "all models for openai failed") {
		t.Errorf("expected all models failed error, got: %v", err)
	}

	conf.ActiveProvider = "unknown"
	err = runAnalyzer(msgPath, conf, info)
	if err == nil || !strings.Contains(err.Error(), "not found in config") {
		t.Errorf("expected unknown provider config error, got %v", err)
	}

	conf.ActiveProvider = "claude"
	generateWithRetry = func(ctx context.Context, p llmprovider.Provider, prompt string, retries int, delay time.Duration) (string, error) {
		return "feat: claude", nil
	}
	if err := runAnalyzer(msgPath, conf, info); err != nil {
		t.Error("claude failed")
	}

	conf.ActiveProvider = "gemini"
	if err := runAnalyzer(msgPath, conf, info); err != nil {
		t.Error("gemini failed")
	}

	if err := runAnalyzer(msgPath, conf, &git.Info{}); err != nil {
		t.Error("expected nil on empty info")
	}

	generateWithRetry = func(ctx context.Context, p llmprovider.Provider, prompt string, retries int, delay time.Duration) (string, error) {
		return "bad", nil
	}
	err = runAnalyzer(msgPath, conf, info)
	if err == nil || !strings.Contains(err.Error(), "all models for gemini failed") {
		t.Errorf("expected all-models-failed error after every model returned unusable output, got: %v", err)
	}

	// Empty API key after clearing config + env
	conf.ActiveProvider = "openai"
	pc := conf.Providers["openai"]
	pc.APIKey = ""
	conf.Providers["openai"] = pc
	oldEnv := osGetenv
	osGetenv = func(string) string { return "" }
	defer func() { osGetenv = oldEnv }()
	err = runAnalyzer(msgPath, conf, info)
	if err == nil || !strings.Contains(err.Error(), "no API key") {
		t.Errorf("expected no API key error, got %v", err)
	}
}

// TestRunAnalyzer_FallbackAfterEmptyPrimary is the regression test for the
// fallback-loop bug: a primary model that returns a successful but unusable
// response (empty, filler, or short) must NOT short-circuit the loop. The
// configured fallback must still be tried, and if it returns a valid message
// it must be written to COMMIT_EDITMSG.
func TestRunAnalyzer_FallbackAfterEmptyPrimary(t *testing.T) {
	oldHook := generateWithRetry
	defer func() { generateWithRetry = oldHook }()

	conf := &config.Config{
		ActiveProvider: "gemini",
		Providers: map[string]config.ProviderConfig{
			"gemini": {APIKey: "test", Model: "primary", FallbackModels: []string{"fallback"}},
		},
		TimeoutSeconds: 5,
	}
	config.ApplyDefaults(conf)

	dir := t.TempDir()
	msgPath := filepath.Join(dir, "COMMIT_EDITMSG")
	if err := os.WriteFile(msgPath, []byte(""), 0o644); err != nil {
		t.Fatal(err)
	}
	info := &git.Info{Files: []string{"a.go"}, Additions: 1, Deletions: 0}

	cases := []struct {
		name    string
		primary string
	}{
		{"empty success", ""},
		{"only filler prefix", "Based on"},
		{"only separator", "---"},
		{"short post-cleanup", "ab"},
		{"whitespace only", "   \n   "},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			calls := 0
			generateWithRetry = func(ctx context.Context, p llmprovider.Provider, prompt string, retries int, delay time.Duration) (string, error) {
				calls++
				if calls == 1 {
					return tc.primary, nil
				}
				return "feat: fallback message succeeded", nil
			}

			if err := runAnalyzer(msgPath, conf, info); err != nil {
				t.Fatalf("fallback should have produced a valid message, got: %v", err)
			}
			if calls != 2 {
				t.Errorf("expected 2 model calls (primary then fallback), got %d", calls)
			}

			got, err := os.ReadFile(msgPath)
			if err != nil {
				t.Fatal(err)
			}
			if !strings.Contains(string(got), "feat: fallback message succeeded") {
				t.Errorf("fallback message not written to COMMIT_EDITMSG; file:\n%s", got)
			}
		})
	}
}

// TestRunAnalyzer_AllModelsReturnUnusable documents that when every model
// returns a successful but unusable response, runAnalyzer surfaces a clear
// "all models failed" error instead of the previous cryptic "too short".
func TestRunAnalyzer_AllModelsReturnUnusable(t *testing.T) {
	oldHook := generateWithRetry
	defer func() { generateWithRetry = oldHook }()

	conf := &config.Config{
		ActiveProvider: "gemini",
		Providers: map[string]config.ProviderConfig{
			"gemini": {APIKey: "test", Model: "p1", FallbackModels: []string{"p2", "p3"}},
		},
		TimeoutSeconds: 5,
	}
	config.ApplyDefaults(conf)

	dir := t.TempDir()
	msgPath := filepath.Join(dir, "COMMIT_EDITMSG")
	if err := os.WriteFile(msgPath, []byte(""), 0o644); err != nil {
		t.Fatal(err)
	}
	info := &git.Info{Files: []string{"a.go"}, Additions: 1}

	calls := 0
	generateWithRetry = func(ctx context.Context, p llmprovider.Provider, prompt string, retries int, delay time.Duration) (string, error) {
		calls++
		return "x", nil
	}

	err := runAnalyzer(msgPath, conf, info)
	if err == nil {
		t.Fatal("expected error when every model returns unusable output")
	}
	if !strings.Contains(err.Error(), "all models for gemini failed") {
		t.Errorf("expected 'all models for gemini failed' error, got: %v", err)
	}
	if calls != 3 {
		t.Errorf("expected 3 model calls (primary + 2 fallbacks), got %d", calls)
	}
}

func TestRunAnalyzer_EnvKeyFallback(t *testing.T) {
	oldHook := generateWithRetry
	defer func() { generateWithRetry = oldHook }()
	oldEnv := osGetenv
	defer func() { osGetenv = oldEnv }()

	osGetenv = func(k string) string {
		if k == "OPENAI_API_KEY" {
			return "from-env"
		}
		return ""
	}
	generateWithRetry = func(ctx context.Context, p llmprovider.Provider, prompt string, retries int, delay time.Duration) (string, error) {
		return "feat: from env key path", nil
	}

	conf := &config.Config{
		ActiveProvider: "openai",
		Providers: map[string]config.ProviderConfig{
			"openai": {APIKey: "", Model: "gpt-4o"},
		},
		TimeoutSeconds: 5,
	}
	config.ApplyDefaults(conf)

	dir := t.TempDir()
	msgPath := filepath.Join(dir, "COMMIT_EDITMSG")
	_ = os.WriteFile(msgPath, []byte(""), 0o644)

	info := &git.Info{Files: []string{"a.go"}, Additions: 1}
	if err := runAnalyzer(msgPath, conf, info); err != nil {
		t.Fatalf("expected env key to satisfy preflight: %v", err)
	}
}

// captureStderr runs fn with the process's stderr sent to a pipe, and returns
// what fn wrote there.
func captureStderr(t *testing.T, fn func()) string {
	t.Helper()
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	prev := os.Stderr
	os.Stderr = w
	t.Cleanup(func() { os.Stderr = prev })
	out := make(chan []byte)
	go func() {
		b, _ := io.ReadAll(r)
		out <- b
	}()
	fn()
	os.Stderr = prev
	if err := w.Close(); err != nil {
		t.Fatal(err)
	}
	return string(<-out)
}

// TestRunAnalyzer_FailureKinds pins which failures of the primary model let
// the fallback run. A refusal and "not permitted" do (0009-MADR D1, D2); an
// authentication failure stops the run before the fallback is asked.
func TestRunAnalyzer_FailureKinds(t *testing.T) {
	oldHook := generateWithRetry
	t.Cleanup(func() { generateWithRetry = oldHook })

	conf := &config.Config{
		ActiveProvider: "openai",
		Providers: map[string]config.ProviderConfig{
			"openai": {APIKey: "test", Model: "primary", FallbackModels: []string{"fallback"}},
		},
		TimeoutSeconds: 5,
	}
	config.ApplyDefaults(conf)
	info := &git.Info{Files: []string{"a.go"}, Additions: 1}

	for _, tc := range []struct {
		name         string
		primaryErr   error
		wantFallback bool
		wantStderr   string
	}{
		{"refusal", fmt.Errorf("%w: I'm sorry, but I can't help with that request.", errRefused), true,
			"model primary failed: model refused the request"},
		{"not permitted", &llmprovider.APIError{Provider: "opencode-go", Status: 403, Kind: llmprovider.ErrNotPermitted}, true,
			"model primary failed: llmprovider: not permitted"},
		{"authentication failure", &llmprovider.APIError{Provider: "openai", Status: 401, Kind: llmprovider.ErrAuthFailure}, false, ""},
	} {
		t.Run(tc.name, func(t *testing.T) {
			msgPath := filepath.Join(t.TempDir(), "COMMIT_EDITMSG")
			if err := os.WriteFile(msgPath, []byte(""), 0o644); err != nil {
				t.Fatal(err)
			}
			calls := 0
			generateWithRetry = func(context.Context, llmprovider.Provider, string, int, time.Duration) (string, error) {
				calls++
				if calls == 1 {
					return "", tc.primaryErr
				}
				return "feat: fallback answered", nil
			}
			var err error
			stderr := captureStderr(t, func() { err = runAnalyzer(msgPath, conf, info) })
			got, readErr := os.ReadFile(msgPath)
			if readErr != nil {
				t.Fatal(readErr)
			}
			if !tc.wantFallback {
				if err == nil || !strings.Contains(err.Error(), "authentication failed for openai") || calls != 1 {
					t.Fatalf("err = %v after %d calls; want the run stopped with authentication failed after 1", err, calls)
				}
				if len(got) != 0 {
					t.Fatalf("message written after an authentication failure:\n%s", got)
				}
				return
			}
			if err != nil || calls != 2 || !strings.Contains(string(got), "feat: fallback answered") {
				t.Fatalf("err = %v after %d calls, message %q; want the fallback's message after 2", err, calls, got)
			}
			if !strings.Contains(stderr, tc.wantStderr) {
				t.Fatalf("stderr %q does not report %q", stderr, tc.wantStderr)
			}
		})
	}
}
