package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/maccavelli/mcplib/llmprovider"
	"github.com/maccavelli/prepare-commit-msg/internal/config"
	"github.com/maccavelli/prepare-commit-msg/internal/git"
)

func TestCleanLLMOutput(t *testing.T) {
	cases := []struct {
		input    string
		expected string
	}{
		{"", ""},
		{"   ", ""},
		{
			"```\nfeat: my message\n```",
			"feat: my message",
		},
		{
			"Here is the commit message:\n\nfeat: some message\n",
			"feat: some message",
		},
		{
			"Generate a commit message:\n---",
			"",
		},
		{
			"```json\n{bad}\n```\nfeat: test",
			"{bad}\nfeat: test",
		},
		{
			"feat: crlf\r\n\r\nbody\r\n",
			"feat: crlf\n\nbody",
		},
	}

	for _, c := range cases {
		out := cleanLLMOutput(c.input)
		if out != c.expected {
			t.Errorf("cleanLLMOutput(%q) = %q; want %q", c.input, out, c.expected)
		}
	}
}

func TestBuildPrompt(t *testing.T) {
	info := &git.Info{
		Files:     []string{"main.go"},
		Stats:     "Scripts: 1",
		Additions: 5,
		Deletions: 2,
		Diff:      "mock diff",
	}
	out := buildPrompt(info)
	if !strings.Contains(out, "main.go") || !strings.Contains(out, "Scripts: 1") {
		t.Error("buildPrompt missing expected info")
	}
}

func TestWriteMessage(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "COMMIT_EDITMSG")
	if err := os.WriteFile(path, []byte("# existing"), 0o644); err != nil {
		t.Fatal(err)
	}

	info := &git.Info{Files: []string{"test.go"}, Additions: 1, Deletions: 0, Stats: "Scripts: 1"}
	if err := writeMessage(path, "feat: test", info); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	text := string(data)
	if !strings.Contains(text, "feat: test") {
		t.Error("missing message")
	}
	if !strings.Contains(text, "# AI-generated") {
		t.Error("missing metadata comment")
	}
	if !strings.Contains(text, "# existing") {
		t.Error("did not preserve existing content")
	}

	if err := writeMessage("/nonexistent/dir/file", "hello", info); err == nil {
		t.Error("expected IO error")
	}
}

func TestShouldSkipSource(t *testing.T) {
	cases := map[string]bool{
		"":         false,
		"template": false,
		"message":  true,
		"merge":    true,
		"squash":   true,
		"commit":   true,
		"unknown":  true,
	}
	for src, want := range cases {
		if got := shouldSkipSource(src); got != want {
			t.Errorf("shouldSkipSource(%q)=%v want %v", src, got, want)
		}
	}
}

func TestRunAnalyzer(t *testing.T) {
	oldHook := generateWithRetry
	defer func() { generateWithRetry = oldHook }()

	conf := &config.Config{
		ActiveProvider: "openai",
		Providers: map[string]config.ProviderConfig{
			"openai": {APIKey: "test", Model: "bad-model", FallbackModels: []string{"good-model"}},
			"claude": {APIKey: "test", Model: "bad-model", FallbackModels: []string{"good-model"}},
			"gemini": {APIKey: "test", Model: "bad-model", FallbackModels: []string{"good-model"}},
		},
		TimeoutSeconds: 5,
	}
	config.ApplyDefaults(conf)

	info := &git.Info{Files: []string{"app.go"}, Additions: 1, Deletions: 1}

	dir := t.TempDir()
	msgPath := filepath.Join(dir, "COMMIT_EDITMSG")
	if err := os.WriteFile(msgPath, []byte(""), 0o644); err != nil {
		t.Fatal(err)
	}

	var fallbackAttempted bool
	generateWithRetry = func(ctx context.Context, p llmprovider.Provider, prompt string, retries int, delay time.Duration) (string, error) {
		if !fallbackAttempted {
			fallbackAttempted = true
			return "", fmt.Errorf("first model fails")
		}
		return "feat: valid message generated by fallback", nil
	}

	if err := runAnalyzer(msgPath, conf, info); err != nil {
		t.Errorf("expected success on fallback: %v", err)
	}

	fallbackAttempted = false
	generateWithRetry = func(ctx context.Context, p llmprovider.Provider, prompt string, retries int, delay time.Duration) (string, error) {
		return "", fmt.Errorf("all fail")
	}
	err := runAnalyzer(msgPath, conf, info)
	if err == nil || !strings.Contains(err.Error(), "all models for openai failed") {
		t.Errorf("expected all models failed error, got: %v", err)
	}

	conf.ActiveProvider = "unknown"
	err = runAnalyzer(msgPath, conf, info)
	if err == nil || !strings.Contains(err.Error(), "not found in config") {
		t.Errorf("expected unknown provider config error, got %v", err)
	}

	conf.ActiveProvider = "claude"
	generateWithRetry = func(ctx context.Context, p llmprovider.Provider, prompt string, retries int, delay time.Duration) (string, error) {
		return "feat: claude", nil
	}
	if err := runAnalyzer(msgPath, conf, info); err != nil {
		t.Error("claude failed")
	}

	conf.ActiveProvider = "gemini"
	if err := runAnalyzer(msgPath, conf, info); err != nil {
		t.Error("gemini failed")
	}

	if err := runAnalyzer(msgPath, conf, &git.Info{}); err != nil {
		t.Error("expected nil on empty info")
	}

	generateWithRetry = func(ctx context.Context, p llmprovider.Provider, prompt string, retries int, delay time.Duration) (string, error) {
		return "bad", nil
	}
	err = runAnalyzer(msgPath, conf, info)
	if err == nil || !strings.Contains(err.Error(), "AI message too short") {
		t.Errorf("expected too short error")
	}

	// Empty API key after clearing config + env
	conf.ActiveProvider = "openai"
	pc := conf.Providers["openai"]
	pc.APIKey = ""
	conf.Providers["openai"] = pc
	oldEnv := osGetenv
	osGetenv = func(string) string { return "" }
	defer func() { osGetenv = oldEnv }()
	err = runAnalyzer(msgPath, conf, info)
	if err == nil || !strings.Contains(err.Error(), "no API key") {
		t.Errorf("expected no API key error, got %v", err)
	}
}

func TestRunAnalyzer_EnvKeyFallback(t *testing.T) {
	oldHook := generateWithRetry
	defer func() { generateWithRetry = oldHook }()
	oldEnv := osGetenv
	defer func() { osGetenv = oldEnv }()

	osGetenv = func(k string) string {
		if k == "OPENAI_API_KEY" {
			return "from-env"
		}
		return ""
	}
	generateWithRetry = func(ctx context.Context, p llmprovider.Provider, prompt string, retries int, delay time.Duration) (string, error) {
		return "feat: from env key path", nil
	}

	conf := &config.Config{
		ActiveProvider: "openai",
		Providers: map[string]config.ProviderConfig{
			"openai": {APIKey: "", Model: "gpt-4o"},
		},
		TimeoutSeconds: 5,
	}
	config.ApplyDefaults(conf)

	dir := t.TempDir()
	msgPath := filepath.Join(dir, "COMMIT_EDITMSG")
	_ = os.WriteFile(msgPath, []byte(""), 0o644)

	info := &git.Info{Files: []string{"a.go"}, Additions: 1}
	if err := runAnalyzer(msgPath, conf, info); err != nil {
		t.Fatalf("expected env key to satisfy preflight: %v", err)
	}
}
